spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: yh123
mybatis:
  type-aliases-package: com.neuedu.busines.pojo
  mapper-locations: classpath:mybatis/BusinessMapper.xml
